version: '3'
name: home-dashboard

services:
  mariadb:
    image: mariadb:11.3.2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dev123
      MYSQL_DATABASE: home_dashboard
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - "3306:3306"
    volumes:
      - maria_data:/var/lib/mysql

volumes:
  maria_data:
